[build.env]
passthrough = [
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_AZURE_CONNECTION_STRING",
    "SCCACHE_AZURE_BLOB_CONTAINER",
    "SCCACHE_DIR",
    "MAJOR_VERSION",
    "SRC_PATH",
    "DEST_PATH",
    "RUST_BACKTRACE",
    "LIBCEC_VENDORED",
    "LIBCEC_NO_VENDOR",
    "LIBCEC_STATIC",
]

[target.aarch64-unknown-linux-gnu]
image="ssalonen/aarch64-unknown-linux-gnu-0.2.1"

[target.arm-unknown-linux-gnueabi]
image="ssalonen/arm-unknown-linux-gnueabi-0.2.1"

[target.armv7-unknown-linux-gnueabihf]
image="ssalonen/armv7-unknown-linux-gnueabihf-0.2.1"

[target.i686-unknown-linux-gnu]
image="ssalonen/i686-unknown-linux-gnu-0.2.1"

[target.i686-unknown-linux-musl]
image="ssalonen/i686-unknown-linux-musl-0.2.1"

[target.mips-unknown-linux-gnu]
image="ssalonen/mips-unknown-linux-gnu-0.2.1"

[target.mips64-unknown-linux-gnuabi64]
image="ssalonen/mips64-unknown-linux-gnuabi64-0.2.1"

[target.mips64el-unknown-linux-gnuabi64]
image="ssalonen/mips64el-unknown-linux-gnuabi64-0.2.1"

[target.mipsel-unknown-linux-gnu]
image="ssalonen/mipsel-unknown-linux-gnu-0.2.1"

[target.x86_64-unknown-linux-gnu]
image="ssalonen/x86_64-unknown-linux-gnu-0.2.1"

[target.x86_64-unknown-linux-musl]
image="ssalonen/x86_64-unknown-linux-musl-0.2.1"

[target.x86_64-pc-windows-gnu]
image="ssalonen/x86_64-pc-windows-gnu-0.2.1"

