[build.env]
passthrough = [
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_AZURE_CONNECTION_STRING",
    "SCCACHE_AZURE_BLOB_CONTAINER",
    "SCCACHE_DIR",
    "MAJOR_VERSION",
    "SRC_PATH",
    "DEST_PATH",
    "RUST_BACKTRACE",
    "LIBCEC_VENDORED",
    "LIBCEC_NO_VENDOR",
    "LIBCEC_STATIC",
]

[target.aarch64-unknown-linux-gnu]
image="ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.arm-unknown-linux-gnueabi]
image="ghcr.io/cross-rs/arm-unknown-linux-gnueabi:main"

[target.armv7-unknown-linux-gnueabihf]
image="ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.i686-unknown-linux-gnu]
image="ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.i686-unknown-linux-musl]
image="ghcr.io/cross-rs/i686-unknown-linux-musl:main"

[target.mips-unknown-linux-gnu]
image="ghcr.io/cross-rs/mips-unknown-linux-gnu:main"

[target.mips64-unknown-linux-gnuabi64]
image="ghcr.io/cross-rs/mips64-unknown-linux-gnuabi64:main"

[target.mips64el-unknown-linux-gnuabi64]
image="ghcr.io/cross-rs/mips64el-unknown-linux-gnuabi64:main"

[target.mipsel-unknown-linux-gnu]
image="ghcr.io/cross-rs/mipsel-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
image="ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
image="ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.x86_64-pc-windows-gnu]
image="docker.io/ssalonen/x86_64-pc-windows-gnu-0.2.1"

